title: Natural Born Fraggers
resources:
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/button-entity-row/button-entity-row.js
  - type: js
    url: /community_plugin/calendar-card/calendar-card.js
  - type: module
    url: /community_plugin/circle-sensor-card/circle-sensor-card.js
  - type: module
    url: /community_plugin/decluttering-card/decluttering-card.js
  - type: js
    url: /community_plugin/flex-table-card/flex-table-card.js
  - type: js
    url: /community_plugin/light-entity-card/light-entity-card.js
  - type: module
    url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
  - type: js
    url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: js
    url: /local/cards/tiles-card.js
  - type: js
    url: /local/cards/monster-card.js
  - type: js
    url: /local/cards/battery-entity.js
  - type: module
    url: /community_plugin/lovelace-auto-entities/auto-entities.js
  - type: module
    url: /community_plugin/swipe-card/swipe-card.js
  - type: js
    url: /community_plugin/github-card/github-card.js
  - type: js
    url: /community_plugin/logbook-card/logbook-card.js
  - type: js
    url: /community_plugin/group-card/group-card.js
  - type: js
    url: /community_plugin/fan-control-entity-row/fan-control-entity-row.js
  - type: module
    url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: module
    url: /community_plugin/lovelace-gap-card/gap-card.js
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: module
    url: /community_plugin/lovelace-more-info-card/more-info-card.js
  - type: module
    url: /community_plugin/lovelace-gui-sandbox/gui-sandbox.js
views: 
  - !include lovelace/views/home.yaml
  - !include lovelace/views/bathroom.yaml
  - !include lovelace/views/living_room.yaml
