switch:
  - platform: switchbot
    name: Living Room Blisslight Switchbot
    mac: 'c9:ec:7b:75:e1:68'
  - platform: template
    switches:
      living_room_blisslight:
        value_template: "{{ is_state('switch.living_room_blisslight_outlet', 'on') }}"
        turn_on:
          service: script.living_room_blisslight_toggle
        turn_off:
          service: script.living_room_blisslight_toggle


input_number:
  living_room_blisslight_sleep:
    name: Living Room Blisslight Sleep 
    initial: 30
    min: 1 
    max: 120 
    step: 1

script:
  living_room_blisslight_toggle:
    sequence:
      - service: switch.toggle 
        entity_id: switch.living_room_blisslight_outlet
      - delay:
          seconds: 2 
      - condition: state
        entity_id: switch.living_room_blisslight_outlet
        state: 'on'
      - service: switch.toggle 
        entity_id: switch.living_room_blisslight_switchbot
  living_room_blisslight_mode:
    sequence:
      - service: switch.toggle 
        entity_id: switch.living_room_blisslight_switchbot
  living_room_blisslight_sleep:
    sequence:
      - delay:
          minutes: "{{ states('input_number.living_room_blisslight_sleep') | int }}"
      - service: switch.turn_off
        entity_id: switch.living_room_blisslight_outlet

homeassistant:
  customize:
    switch.living_room_blisslight_outlet:
      friendly_name: Living Room Blisslight Outlet
      hidden: true
    script.living_room_blisslight_sleep:
      friendly_name: Living Room Blisslight Sleep
      icon: mdi:power-sleep
    input_number.living_room_blisslight_sleep:
      friendly_name: Living Room Blisslight Sleep
      icon: mdi:clock
    script.living_room_blisslight_mode:
      friendly_name: Living Room Blisslight Mode
      icon: mdi:skip-next-circle 
    script.living_room_blisslight_toggle:
      hidden: true
    switch.living_room_blisslight:
      device_class: switch
      friendly_name: Living Room Blisslight
      icon: mdi:star-circle-outline
